export type hour = {
  apparentTemperature: number,
  cloudCover: number,
  dewPoint: number,
  humidity: number,
  icon: string,
  ozone: number,
  precipAccumulation: number,
  precipIntensity: number,
  precipProbability: number,
  precipType: string,
  pressure: number,
  summary: string,
  temperature: number,
  time: number,
  uvIndex: number,
  visibility: number,
  windBearing: number,
  windGust: number,
  windSpeed: number,
}